name: dev-begin
description: "Initialize development environment for a story - handles git state, dependency validation, and worktree/branch setup before invoking dev-story"
author: "BMad"
template: false

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
bmad_folder: "{config_source}:bmad_folder"
date: system-generated

# Path Segregation (alpha.20) - separates ephemeral from permanent artifacts
planning_artifacts: "{config_source}:planning_artifacts"
implementation_artifacts: "{config_source}:implementation_artifacts"
output_folder: "{planning_artifacts}"
story_dir: "{implementation_artifacts}"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/dev-begin"
instructions: "{installed_path}/instructions.xml"

# Input - story ID is optional, will auto-detect if empty
story_id: ""

# File references
sprint_status: "{implementation_artifacts}/sprint-status.yaml"
worktree_base: "{project-root}/.worktrees"

# Workflow to invoke after setup
dev_story_workflow: "{project-root}/_bmad/bmm/workflows/4-implementation/dev-story"

standalone: true
web_bundle: false
