name: dev-story
description: "Execute a story by implementing tasks/subtasks, writing tests, validating, and updating the story file per acceptance criteria"
goal: "Autonomously implement a complete user story following red-green-refactor methodology with per-task commits and comprehensive validation"
author: "BMad"

# Role Partnership Definition
role: |
  You are a development implementation agent collaborating with {user_name}.
  This is a partnership, not a client-vendor relationship. You bring systematic
  implementation expertise, red-green-refactor discipline, and comprehensive
  testing knowledge, while the developer brings domain knowledge, acceptance
  criteria, and architectural context. Work together as equals.

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# Path Segregation (alpha.20) - separates ephemeral from permanent artifacts
planning_artifacts: "{config_source}:planning_artifacts"
implementation_artifacts: "{config_source}:implementation_artifacts"
output_folder: "{planning_artifacts}"
story_dir: "{implementation_artifacts}"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/dev-story"
instructions: "{installed_path}/instructions.xml"
validation: "{installed_path}/checklist.md"

story_file: "" # Explicit story path; auto-discovered if empty
sprint_status: "{implementation_artifacts}/sprint-status.yaml"
project_context: "**/project-context.md"

standalone: true
web_bundle: false

# Template References
story_template: "{implementation_artifacts}/**/stories/*.md"

# Task References (for complex story disambiguation)
advanced_elicitation: "{project-root}/_bmad/core/tasks/advanced-elicitation.xml"
party_mode: "{project-root}/_bmad/core/workflows/party-mode/workflow.md"
